

apiVersion: apps/v1
kind: Deployment                                          # 1
metadata:
  name: sample-frontend
  labels:
    app: sample-frontend
spec:
  selector:
    matchLabels:
      app: sample-frontend
  replicas: 1                                             # 2
  minReadySeconds: 15
  strategy:
    type: RollingUpdate                                   # 3
    rollingUpdate: 
      maxUnavailable: 1                                   # 4
      maxSurge: 1                                         # 5
  template:
    metadata:
      labels:
        app: sample-frontend                                  # 6
    spec:
      serviceAccountName: coit-frontend
      containers:
        - image: jaseem180/sample-app-frontend:latest
          imagePullPolicy: IfNotPresent                         # 7
          name: sample-frontend
          livenessProbe:
            exec:
              command:
              - ls
              - /
            initialDelaySeconds: 5
            periodSeconds: 5
          readinessProbe:
            tcpSocket:
              port: 80
            initialDelaySeconds: 10
            periodSeconds: 10
          resources:
            requests:
              cpu: 10m
              memory: 250M
            limits: 
              cpu: 150m
              memory: 450M
          ports:
            - containerPort: 80
